# Generated by Django 2.0 on 2018-11-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
